-- MySQL Script generated by MySQL Workbench
-- qui 09 fev 2023 02:11:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema investimentos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema investimentos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `investimentos` ;
USE `investimentos` ;

-- -----------------------------------------------------
-- Table `investimentos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `identidade` VARCHAR(10) NOT NULL,
  `filiacao` VARCHAR(60) NOT NULL,
  `sexo` SET('M', 'F', 'O') NOT NULL,
  `estado_civil` SET("solteiro", "namorando", "casado", "separado", "divorciado", "viuvo") NOT NULL,
  `naturalidade` VARCHAR(60) NOT NULL,
  `cidade` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `rua` VARCHAR(60) NOT NULL,
  `numero` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `uf` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `pais` VARCHAR(60) NOT NULL,
  `escolaridade` VARCHAR(60) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `id_bancario` INT NOT NULL,
  `codigo_agencia` VARCHAR(6) NOT NULL,
  `conta_corrente` VARCHAR(7) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `renda_mensal` FLOAT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimentos`.`tesouro_direto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`tesouro_direto` (
  `id_tesouro_direto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `indexador` VARCHAR(10) NOT NULL,
  `tx_juro_mensal` DECIMAL(2) NOT NULL,
  `valor_unitario` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_tesouro_direto`),
  UNIQUE INDEX `id_tesouro_direto_UNIQUE` (`id_tesouro_direto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimentos`.`tesouro_direto_carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`tesouro_direto_carteira` (
  `id_tesouro_direto_carteira` INT NOT NULL,
  `tesouro_direto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `usuario_carteira` INT NOT NULL,
  PRIMARY KEY (`id_tesouro_direto_carteira`),
  INDEX `fk_tesouro_direto_carteira_1_idx` (`usuario_carteira` ASC) VISIBLE,
  INDEX `fk_tesouro_direto_carteira_2_idx` (`tesouro_direto_id` ASC) VISIBLE,
  CONSTRAINT `fk_tesouro_direto_carteira_1`
    FOREIGN KEY (`usuario_carteira`)
    REFERENCES `investimentos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tesouro_direto_carteira_2`
    FOREIGN KEY (`tesouro_direto_id`)
    REFERENCES `investimentos`.`tesouro_direto` (`id_tesouro_direto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimentos`.`fundo_investimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`fundo_investimento` (
  `id_fundo_investimento` INT NOT NULL AUTO_INCREMENT,
  `classe` VARCHAR(12) NOT NULL,
  `prazo_resgate` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `valor_minimo` DECIMAL(2) NOT NULL,
  `data_resgate` DATE NOT NULL,
  PRIMARY KEY (`id_fundo_investimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimentos`.`fundo_investimento_carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`fundo_investimento_carteira` (
  `id_fundo_de_investimentos_carteira` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_carteira` INT NOT NULL,
  `fundo_investimento_id` INT NOT NULL,
  PRIMARY KEY (`id_fundo_de_investimentos_carteira`),
  INDEX `fk_fundo_de_investimentos_carteira_1_idx` (`id_usuario_carteira` ASC) VISIBLE,
  INDEX `fk_fundo_de_investimentos_carteira_2_idx` (`fundo_investimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_fundo_de_investimentos_carteira_1`
    FOREIGN KEY (`id_usuario_carteira`)
    REFERENCES `investimentos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fundo_de_investimentos_carteira_2`
    FOREIGN KEY (`fundo_investimento_id`)
    REFERENCES `investimentos`.`fundo_investimento` (`id_fundo_investimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimentos`.`renda_fixa_variavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`renda_fixa_variavel` (
  `id_renda_fixa_variavel` INT NOT NULL,
  `classe` INT NOT NULL,
  `empresa_emissora` VARCHAR(60) NOT NULL,
  `prazo_vencimento` INT NOT NULL,
  `taxa_remuneracao` INT NOT NULL,
  `horario_limite` TIME NOT NULL,
  `valor_minimo` DECIMAL NOT NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`id_renda_fixa_variavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimentos`.`renda_fixa_variavel_carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`renda_fixa_variavel_carteira` (
  `id_renda_fixa_variavel_carteira` INT NOT NULL,
  `id_usuario_carteira` INT NOT NULL,
  `id_renda_fixa_variavel` INT NOT NULL,
  PRIMARY KEY (`id_renda_fixa_variavel_carteira`),
  INDEX `fk_demais_investimentos_carteira_1_idx` (`id_usuario_carteira` ASC) VISIBLE,
  INDEX `fk_demais_investimentos_carteira_2_idx` (`id_renda_fixa_variavel` ASC) VISIBLE,
  CONSTRAINT `fk_demais_investimentos_carteira_1`
    FOREIGN KEY (`id_usuario_carteira`)
    REFERENCES `investimentos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_demais_investimentos_carteira_2`
    FOREIGN KEY (`id_renda_fixa_variavel`)
    REFERENCES `investimentos`.`renda_fixa_variavel` (`id_renda_fixa_variavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investimentos`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investimentos`.`telefone` (
  `id_telefones` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `telefone` VARCHAR(14) NULL,
  PRIMARY KEY (`id_telefones`),
  INDEX `fk_telefones_1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `investimentos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
